### ISSUE TITLE
部分标点符号位置未遵循中国大陆标准

### ISSUE THREAD

**Issue by catwalk2005** [lxgw/LxgwNewClearGothic#2]
根据《GB/T 15834—2011 标点符号用法》中第 5.2.1 条阐述：
「5.2.1　句号、问号、叹号、逗号、顿号、分号和冒号均置于相应文字之下偏右。」
既然字形选择了遵循中国大陆标准，为何不让标点符号也一并遵循呢？

**Comment by catwalk2005** [comment]
<img width="440" alt="屏幕截图 2021-03-16 182132" src="https://user-images.githubusercontent.com/80753591/111295261-22a65d80-8686-11eb-9fd2-45b00cba616d.png">

**Comment by catwalk2005** [comment]
<img width="521" alt="屏幕截图 2021-03-16 181617" src="https://user-images.githubusercontent.com/80753591/111295294-2c2fc580-8686-11eb-8d81-5960a4e8781e.png">

**Comment by lxgw** [comment]
这个是我自己的取舍，私以为竖排标点符号居中更加美观。
